-- Perscadors — HP Looks : identité et prix automatique

begin;

-- La table historique utilisait id integer primary key sans génération automatique.
-- Cela faisait échouer createOutfit() lorsque l'admin ne fournissait pas d'id.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'outfits' and column_name = 'id' and is_identity = 'NO'
  ) then
    alter table public.outfits alter column id add generated by default as identity;
  end if;
end $$;

create or replace function public.recalculate_outfit_price(product_ids_input integer[])
returns numeric
language sql
stable
set search_path = public
as $$
  select coalesce(sum(price), 0)
  from public.products
  where id = any(coalesce(product_ids_input, '{}'::integer[]));
$$;

create or replace function public.set_outfit_price()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.custom_price = public.recalculate_outfit_price(new.product_ids);
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists outfits_recalculate_price on public.outfits;
create trigger outfits_recalculate_price
before insert or update of product_ids on public.outfits
for each row execute function public.set_outfit_price();

-- Si le prix d'un produit change, chaque look contenant ce produit est recalculé.
create or replace function public.refresh_outfit_prices_for_product()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  update public.outfits
  set custom_price = public.recalculate_outfit_price(product_ids), updated_at = now()
  where old.id = any(product_ids);
  return new;
end;
$$;

drop trigger if exists products_refresh_outfit_prices on public.products;
create trigger products_refresh_outfit_prices
after update of price on public.products
for each row execute function public.refresh_outfit_prices_for_product();

-- Aligne les looks existants.
update public.outfits
set custom_price = public.recalculate_outfit_price(product_ids), updated_at = now();

commit;
