-- Perscadors — HP Looks : identité et prix automatique
-- product_ids est JSONB dans la base réelle (et non integer[]).

begin;

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'outfits' and column_name = 'id' and is_identity = 'NO'
  ) then
    alter table public.outfits alter column id add generated by default as identity;
  end if;
end $$;

-- Une identité ajoutée à une table existante démarre souvent à 1 :
-- réaligner sa séquence sur les HP Looks déjà présents évite outfits_pkey duplicate.
do $$
declare sequence_name text;
begin
  select pg_get_serial_sequence('public.outfits', 'id') into sequence_name;
  if sequence_name is not null then
    execute format(
      'select setval(%L, coalesce((select max(id) from public.outfits), 0) + 1, false)',
      sequence_name
    );
  end if;
end $$;

create or replace function public.recalculate_outfit_price(product_ids_input jsonb)
returns numeric
language sql
stable
set search_path = public
as $$
  select coalesce(sum(p.price), 0)
  from public.products p
  where p.id in (
    select value::integer
    from jsonb_array_elements_text(coalesce(product_ids_input, '[]'::jsonb))
    where value ~ '^[0-9]+$'
  );
$$;

create or replace function public.set_outfit_price()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.custom_price = public.recalculate_outfit_price(new.product_ids);
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists outfits_recalculate_price on public.outfits;
create trigger outfits_recalculate_price
before insert or update of product_ids on public.outfits
for each row execute function public.set_outfit_price();

create or replace function public.refresh_outfit_prices_for_product()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  update public.outfits
  set custom_price = public.recalculate_outfit_price(product_ids), updated_at = now()
  where product_ids ? old.id::text;
  return new;
end;
$$;

drop trigger if exists products_refresh_outfit_prices on public.products;
create trigger products_refresh_outfit_prices
after update of price on public.products
for each row execute function public.refresh_outfit_prices_for_product();

update public.outfits
set custom_price = public.recalculate_outfit_price(product_ids), updated_at = now();

commit;
